apiVersion: v1
kind: Service
metadata:
  name: k8s-nodeport-service
spec:
  type: NodePort
  selector:
    app: nodeport-service
  ports:
    - name: nodeport-service
      protocol: TCP
      port: 80
      targetPort: 80